import numpy as np
import analysis_tools

lmr = np.random.rand(23, 3,2, 8,500)
lmr[:,:,0] = lmr[:,:,0] + 1

x_axis_ticks = np.around(np.linspace(0, 100, 8), 2)
lmr2 = np.random.rand(23, 3,2, 500)
lmr2[:,0] = lmr[:,0] + 1
lmr2[:,1] = lmr[:,1] + 2
lmr2[:,2] = lmr[:,2] + 3

lmr2[:,:,0] = lmr[:,:,0] + 1
lmr2[:,:,1] = lmr[:,:,1] + 2

# we will pass this data into hasty plotter. The shape of the data must have an axis which represents different trials (usually axis 0) and an axis that represents time (usually axis -1/ the last axis). Besides those axes, there should be at least one more. If for some reason you don't have a third axis, use numpy.expand_dims so that you get that extra axis (typically this shouldn't happen).

############## pass all your axes information into the hasty plotter object when it initializes.###############

# the trials axis and time axis are used by all of the hasty plotter plots so they should be called only once hasty plotter is instantiated and should remain constant. 
# the 0 axis generated by arraybuilder will always be the "trials axis" so trials axis is usually assumed to be 0 unless you specify it. 
# the "time axis" is usually the last axis so by default it is set to -1 but you can also specify this
# "color_axis" is the axis along which different colors will be plotted on the same graph
# "subplots_axis" is the axis along which different subplots will be made. for now this only works with vertically oriented subplots. 
# " x_axis" is the axis which will represent the x axis of each subplot

plotter0 = analysis_tools.Hasty_plotter(data = lmr, plot_title = 'example plots 3D', trial_axis = 0, time_axis = 4, color_axis = 2, color_labels = ['cold', 'warm'], subplot_axis = 1, subplot_labels = ['slow', 'med', 'fast'], x_axis = 3, x_ticks = x_axis_ticks, x_label = "magnitude")

# We can select different types of plots from hasty plotter's functions but we need to decide how we want each data axis represented.

plotter0.plot_mean_resp()

# for 2D heatmaps you need a y_axis as well. If not included, it will take the y axis to be the colors axis
plotter0.plot_mean_resp_heatmap()

plotter0.plot_indv_mean_resps()

plotter1 = analysis_tools.Hasty_plotter(data = lmr2, plot_title = 'example plots 2D', starting_fig_num = len(plotter0.figs), color_axis = 2, color_labels = ['cold', 'warm'], subplot_axis = 1, subplot_labels = ['slow', 'med', 'fast']) # assumes trials axis is 0 and time axis is -1. setting the starting figure number ensures we aren't overwriting figures from previous plotter.

plotter1.plot_time_series()
plotter1.plot_time_series(color_axis = 1, subplot_axis = 2)

# a hasty plotter object provides access to individual figures and subplots that it creates so you can always make fine adjustments to plots afterwards.
ylabels = ['voltage', 'height',  'weight']
for i_ax, ax in enumerate(plotter1.figs[0].axes):
    ax.set_ylabel(ylabels[i_ax])

# hasty plotter comes with some convenience functions to manipulate all subplots in a figure simultaneously       
plotter1.eq_ylims(fig_ind = 0)

# for easy switching between plots, you can store the axes arguments in a hasty plotter object and just call plots


plotter2 =analysis_tools.Hasty_plotter(data = lmr2, trial_axis = 0, color_axis = 2, x_axis = 1, time_axis = 3, starting_fig_num = len(plotter1.figs) + len(plotter0.figs))
plotter2.plot_mean_resp()

