import numpy as np
import analysis_tools

lmr = np.random.rand(23, 3,2, 8,500)
lmr[:,:,0] = lmr[:,:,0] + 1

x_axis_labels = np.around(np.linspace(0, 100, 8), 2)
# we will pass this data into hasty plotter. The shape of the data must have an axis which represents different trials (usually axis 0) and an axis that represents time (usually axis -1, the last axis). Besides those axes, there should be at least one more. If for some reason you don't have a third axis, use numpy.expand_dims so that you get that extra axis (typically this shouldn't happen). Also you can set a plot title by passing it as an argument into hasty plotter.

plotter = analysis_tools.Hasty_plotter(data = lmr, plot_title = 'example plots')

# We can select different types of plots from hasty plotter's functions but we need to decide how we want each data axis represented.
# the 0 axis generated by arraybuilder will always be the "trials axis" so trials axis is usually assumed to be 0 unless you specify it. 
# "colors_axis" is the axis along which different colors will be plotted on the same graph
# "subplots_axis" is the axis along which different subplots will be made. for now this only works with one dimensional subplots
# " x_axis" is the axis which will represent the x axis of each subplot

plotter.plot_mean_resp(trials_axis = 0, colors_axis = 2, colors_labels = ['cold', 'warm'], subplots_axis = 1, subplots_labels = ['slow', 'med', 'fast'], x_axis = 3, x_ticks = x_axis_labels, x_label = "magnitude")


